name: qrskit
description: "One-stop QR platform"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.01

environment:
  sdk: ^3.5.3

dependencies:
  action_slider: ^0.7.0
  app_links: ^6.3.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  dotlottie_loader: ^0.0.4
  firebase_app_check: ^0.3.1+4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  firebase_ui_firestore: ^1.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^17.2.4
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  http: ^1.2.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  lottie: ^3.1.3
  marquee: ^2.3.0
  quick_actions: ^1.0.8
  rive: ^0.13.15
  share_plus: ^10.1.1
  sign_in_with_apple: ^6.1.3
  televerse: ^1.26.7
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
