// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-kBH1GuwozV8RVUIh85YM65IERNrTXRM',
    appId: '1:456453587208:web:8906903423b2ab8e0aacbd',
    messagingSenderId: '456453587208',
    projectId: 'qrs-kit',
    authDomain: 'qrs-kit.firebaseapp.com',
    storageBucket: 'qrs-kit.appspot.com',
    measurementId: 'G-XMD69WH6P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8hx36pDugY67yWZsacZ9SaSizo0FauSY',
    appId: '1:456453587208:android:83444429b16305810aacbd',
    messagingSenderId: '456453587208',
    projectId: 'qrs-kit',
    storageBucket: 'qrs-kit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMqyJSJ5FYoENzj97qTjFwcK4bAGr1TbY',
    appId: '1:456453587208:ios:2c36f9d204c698220aacbd',
    messagingSenderId: '456453587208',
    projectId: 'qrs-kit',
    storageBucket: 'qrs-kit.appspot.com',
    iosBundleId: 'com.flikko.qrskit',
  );
}
